{
    'name': 'School Africa Management',
    'version': '1.0',
    'summary': 'Manage school years',
    'author': 'Abdou NDAO',
    'category': 'Education',
    'depends': ['base', 'mail', 'spiffy_theme_backend'],
    'data': [
        'security/ir.model.access.csv',
        'views/school_year_views.xml',
        'views/school_level_views.xml',
        'views/school_period_views.xml',
        'views/school_matiere_views.xml',
        'views/school_professor_views.xml',
        'views/school_class_views.xml',
        'views/school_student_views.xml',
        'views/school_course_views.xml',
        'views/school_evaluation_views.xml',
        'views/school_session_views.xml',
        'views/school_year_menu.xml',
        'data/matiere_data.xml',
        'data/level_data.xml',
    ],
    'installable': True,
    'application': True,
}
